import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthHeader from "@/components/AuthHeader";
import { getUser } from "@/auth/user.action";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // 유저 정보 가져오기
    const user = await getUser();
    console.log("user", user);
    return (
        <html lang="ko">
            <body className={inter.className}>
                <AuthHeader user={user} />
                {children}
            </body>
        </html>
    );
}
